version: "3"

volumes:
  mysql_data:
    driver: local

networks:
  app-network:

services:
  reverse-proxy:
    image: traefik:2.2
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  react:
    build: ./frontend
    restart: always
    networks:
      - app-network
    labels:
      - "traefik.http.services.react-service.loadbalancer.server.port=80"
      - "traefik.http.routers.react-router.rule=Host(`localhost`)"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^http://localhost/google(.*)"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=https://google.com/"
      - "traefik.http.routers.react-router.middlewares=test-redirectregex"
    depends_on:
      - reverse-proxy
  spring-boot:
    build: ./backend
    restart: always
    networks:
      - app-network
    labels:
      - "traefik.http.services.spring-boot-service.loadbalancer.server.port=4200"
      - "traefik.http.routers.spring-boot-router.rule=Host(`localhost`) && PathPrefix(`/api`)"
    depends_on:
      - mysql
      - keycloak
      - reverse-proxy
  mysql:
    image: mysql:8
    volumes:
      - c:\mysql\volumes\docker-compose-demo:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 123
    restart: always
    networks:
      - app-network
    depends_on:
      - reverse-proxy
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_USER: keycloak
      DB_PASSWORD: 123
      DB_DATABASE: keycloak
      # JDBC_PARAMS: "useSSL=false&allowPublicKeyRetrieval=true"
    restart: always
    networks:
      - app-network
    labels:
      - "traefik.http.services.keycloak-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak-router.rule=Host(`localhost`) && PathPrefix(`/auth`)"
    depends_on:
      - mysql
      - reverse-proxy
